version: '3.9'
services: 
  api:
    container_name: api
    build: 
      context: /backend
      dockerfile: ./Dockerfile
    depends_on: 
      - postgres_db
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/pmsoft.pfx
    volumes:
      - ./backend/conf.d/https:/https:ro
  postgres_db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "master"
    ports:
      - "5432:5432"

